### ISSUE TITLE
Deploy automatico

### ISSUE THREAD

**Issue by devrrior** [Python-en-equipo/MarketPlace#62]
- [x] Prepara settings.py para docker y deploy.
- [x] Mejorar Dockerfile.
- [x] Crear una Github Action para deploy automatico en heroku.
- [x] Documentar las mejoras en docker.
- [x] Hacer pruebas en el heroku de prueba.
- [x] Hacer cambios a la configuración de devcontainer.
- [x] Cargar variables de entorno oficiales.

**Comment by devrrior** [comment]
# Documentación del deploy automático
Antes de empezar a configurar el workflow para el deploy automático, hice ciertos cambios en el Dockerfile y docker-compose, incluso elaboré un nuevo Dockerfile para el desarrollo local. Además cambié ciertas cosas en settings.py, para el deploy. Estos cambios los explicaré detalladamente más adelante.
## Cambios en `settings.py`

1. Primero cambie el valor de **DEBUG** por una variable de entorno, esto permitira cambiarlo cuando sea necesario.
2. Para probar la implementacion tuve que realizar el despliegue en un heroku privado, por lo cual tuve que agregar el dominio del heroku privado en **ALLOWED_HOSTS**.
3. Algo importante para que los formularios funcionen, es agregar una variable la cual es **CSRF_TRUSTED_ORIGINS**, esto permitara utilizar los formularios y asi no tengamos problemas con **CSRF_TOKEN**.
4. Al momento de correr el proyecto me dio problemas con una de las aplicaciones (**storages**), por lo que vi no se encuentra la aplicación, asi que lo tuve que comentar.
5. Por último tuve que comentar la configuración de **REDIS**, ya que no se esta utilizando en el despliegue.


```python

DEBUG = env('DEBUG')

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "http://127.0.0.1:8000/", "django-ecommerce-v1.herokuapp.com", "test-marketplace-django.herokuapp.com"]


CSRF_TRUSTED_ORIGINS = ['https://test-marketplace-django.herokuapp.com', 'https://django-ecommerce-v1.herokuapp.com']

# Application definitionds

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "storages",
    "ecommerce",
    "users",
]

# CACHE REDIS
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
#         "KEY_PREFIX": "ecomm",
#     }
# }
```
## Mejoras en `Dockerfile`
En el Docker files hice ciertas mejoras, a continuación las listo:

1. La primera mejora es cambiar la imagen que se utiliza en el contenedor, utilice la imagen alpine, esta imagen nos ofrece la ventaja de que su peso es muy pequeño, por lo que disminuye el tiempo de construcción del contenedor.
2. Otro cambio que realice fue que para aprovechar la cacheabilidad que tiene Docker, fue que en lugar de copiar todo el proyecto, primero copie el requirements-deploy.txt (en este archivo estan las librerias necesarias para correr nuestro proyecto). Despues se actualiza los paquetes de la imagen, instalo ciertos paquetes los cuales son necesarios para la instalación de las librerias que necesita el proeycto y actualizó pip. Una vez hecho esto copio el proyecto al contenedor. Como comentaba al principio hice esto pasos para usar la cacheabilidad, con esto si realizamos algun cambio en el proyecto y queramos correr el contenedor, no tenga que instalar de nuevo las librerias que necesita el proyecto, esto nos ayudará a ahorrar tiempo.
3. Por ultimo creé un script muy básico donde se apliquen las migraciones que hemos creado y después corra el servidor en heroku.

```Dockerfile
FROM python:3.8-alpine3.15

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./requirements-deploy.txt ./

RUN  apk update \
  && apk add --no-cache gcc musl-dev postgresql-dev python3-dev jpeg-dev zlib-dev \
  && pip install --upgrade pip

RUN python -m pip install -r requirements-deploy.txt 

COPY ./ ./

CMD [ "sh", "entrypoint.sh" ]
```

```sh
#!/bin/sh

python manage.py collectstatic --noinput
python manage.py migrate

gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
```

## Creación de `local.Dockerfile
Ademas de crear un Dockerfile para el deploy, creé un Dockerfile para que los desarrolladores puedan correr el proyecto sin ningún problema, el archivo es casi lo mismo, solo que para correr el proyecto lo indico en el docker-compose.
```Dockerfile
FROM python:3.8-alpine3.15

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./requirements.txt ./

RUN  apk update \
  && apk add --no-cache gcc musl-dev postgresql-dev python3-dev  jpeg-dev zlib-dev \
  && pip install --upgrade pip

RUN python -m pip install -r requirements.txt 

COPY ./ ./
```
## Mejoras en `docker-compose.yml
En este archivo modifiqué pocas cosas, es lo siguiente:

1. Primero que nada comente la imagen redis, ya que no se utiliza por el momento.
2. Otra cosa fue que esta utilizando la distribución alpine, la cual como ya comentaba anteriormente, sirve para que la imagen se construye en el menor tiempo posible.
3. Tambien cambié el puerto en el cual comparte entre nuestra computadora personal y el contenedor.
4. En la parte build, cambie el nombre del `Dockerfile`, por `local.Dockerfile`.
5. Ya que en `local.Dockerfile` no indicamos que corra el proyecto, en este archivo le indicamos que haga las migraciones pertinentes y que al final corra nuestro proyecto.
6. Por último en enviroment, agrego las variables de entorno que faltan, tales como `DEBUG` y `DJANGO_KEY`.

```yml
version: '3.4'

services:
  # redis:
  #   restart: always
  #   image: redis:5
  #   ports:
  #     - "6379:6379"

  db:
    restart: always
    #restart: unless-stopped
    image: postgres:14.1-alpine3.15 
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5431:5432 # para que sea visible en nuestro entorno local 
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:    
    restart: always
    container_name: django
    build:      
      context: .
      dockerfile: ./local.Dockerfile
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - ALLOWED_HOSTS=127.0.0.1, localhost     
      - DJANGO_KEY=123
      - DEBUG=True

    volumes:
      - .:/app
    depends_on:
      - db
```
## Cambios en `django-test.yml` para el deploy automático
Para agregar el deploy automático use una Github Action ya precreada, solo agregue la configuración pertinente, tales como:

- heroku_api_key
- heroku_app_name
- heroku_email

Tambien agregue las variables de entorno que necesita nuestro proyecto, estas las pasara a Heroku.

```yml
# some config
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.TEST_HEROKU_API_KEY}}
          heroku_app_name: "test-marketplace-django" #Must be unique in Heroku
          heroku_email: "devrrior@gmail.com"
          usedocker: true
        env:
          HD_POSTGRES_NAME: ${{secrets.TEST_NAME_DB_HEROKU}}
          HD_POSTGRES_USER: ${{secrets.TEST_USER_DB_HEROKU}}
          HD_POSTGRES_PASSWORD: ${{secrets.TEST_PASSWORD_DB_HEROKU}}
          HD_POSTGRES_HOST: ${{secrets.TEST_HOST_DB_HEROKU}}
          HD_DJANGO_KEY: ${{secrets.DJANGO_KEY}}
          HD_DEBUG: ${{secrets.DEBUG}}
          HD_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          HD_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          HD_AWS_STORAGE_BUCKET_NAME: ${{secrets.AWS_STORAGE_BUCKET_NAME}}
```
